### ISSUE TITLE
org.json.JSONException: No value for survey_status

### ISSUE THREAD

**Issue by tanush1191** [SurveyMonkey/surveymonkey-ios-sdk#48]
Hi ,

while launching survey in Android getting the following issue as "org.json.JSONException: No value for survey_status" and not able to launch survey white screen is displayed

Please help  

Regards,
Tanush

**Comment by benleiken** [comment]
@tanush1191 please open this issue on the android sdk -- thanks! https://github.com/SurveyMonkey/surveymonkey-android-sdk

**Comment by tanush1191** [comment]
Still issue has not resolved getting same issue

**Comment by tanush1191** [comment]
org.json.JSONException: No value for survey_status
     em.err:     at org.json.JSONObject.get(JSONObject.java:355)
     at org.json.JSONObject.getJSONObject(JSONObject.java:574)
	 at com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackFragment$1.onPostExecute(SMFeedbackFragment.java:91)
     at com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackFragment$1.onPostExecute(SMFeedbackFragment.java:86)
     at android.os.AsyncTask.finish(AsyncTask.java:632)
     at android.os.AsyncTask.access$600(AsyncTask.java:177)
     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:136)
     at android.app.ActivityThread.main(ActivityThread.java:5584)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:515)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084):     at dalvik.system.NativeStart.main(Native Method)
